import os
import sqlite3
from datetime import datetime, timezone
from decimal import Decimal

from dotenv import load_dotenv

try:
    import psycopg2
    from psycopg2.extras import RealDictCursor
except Exception:  # pragma: no cover
    psycopg2 = None
    RealDictCursor = None

load_dotenv()

DATABASE_URL = os.environ.get("DATABASE_URL", "sqlite:///granja.db")
SQLITE_DATABASE = DATABASE_URL.startswith("sqlite")


def get_db_connection():
    """Abre uma conexão SQLite local ou PostgreSQL/Neon."""
    if SQLITE_DATABASE:
        connection = sqlite3.connect("granja.db")
        connection.row_factory = sqlite3.Row
        return connection

    if psycopg2 is None:
        raise RuntimeError("psycopg2 não está disponível")

    return psycopg2.connect(DATABASE_URL, cursor_factory=RealDictCursor)


def init_db():
    """Cria as tabelas do modelo de eventos de temperatura e uso."""
    connection = get_db_connection()
    cursor = connection.cursor()

    if SQLITE_DATABASE:
        cursor.executescript(
            """
            CREATE TABLE IF NOT EXISTS "Temperatura" (
                "id" INTEGER PRIMARY KEY AUTOINCREMENT,
                "temp" REAL NOT NULL,
                "data_hora" TEXT NOT NULL
            );
            CREATE TABLE IF NOT EXISTS "Tempo de uso" (
                "id" INTEGER PRIMARY KEY AUTOINCREMENT,
                "TempoLigado(minutos)" REAL NOT NULL,
                "inicio" TEXT NOT NULL,
                "fim" TEXT NOT NULL
            );
            CREATE TABLE IF NOT EXISTS "Ativacao" (
                "id" INTEGER PRIMARY KEY AUTOINCREMENT,
                "temperatura_id" INTEGER NOT NULL,
                "tempo_uso_id" INTEGER,
                "temperatura" REAL NOT NULL,
                "TempoLigado" REAL,
                "status_lampada" INTEGER NOT NULL,
                "data_hora" TEXT NOT NULL,
                FOREIGN KEY ("temperatura_id") REFERENCES "Temperatura"("id"),
                FOREIGN KEY ("tempo_uso_id") REFERENCES "Tempo de uso"("id")
            );
            """
        )
    else:
        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS "Temperatura" (
                "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "temp" DECIMAL NOT NULL,
                "data_hora" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
            );
            CREATE TABLE IF NOT EXISTS "Tempo de uso" (
                "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "TempoLigado(minutos)" DECIMAL NOT NULL,
                "inicio" TIMESTAMP NOT NULL,
                "fim" TIMESTAMP NOT NULL
            );
            CREATE TABLE IF NOT EXISTS "Ativacao" (
                "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "temperatura_id" INTEGER NOT NULL REFERENCES "Temperatura"("id"),
                "tempo_uso_id" INTEGER REFERENCES "Tempo de uso"("id"),
                "temperatura" DECIMAL NOT NULL,
                "TempoLigado" DECIMAL,
                "status_lampada" BOOLEAN NOT NULL,
                "data_hora" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
            );
            """
        )
        _migrate_existing_postgres_schema(cursor)

    connection.commit()
    cursor.close()
    connection.close()


def _migrate_existing_postgres_schema(cursor):
    """Completa tabelas criadas pelo script SQL original do projeto."""
    cursor.execute(
        """
        ALTER TABLE "Temperatura"
            ADD COLUMN IF NOT EXISTS "data_hora" TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
        ALTER TABLE "Tempo de uso"
            ADD COLUMN IF NOT EXISTS "inicio" TIMESTAMP,
            ADD COLUMN IF NOT EXISTS "fim" TIMESTAMP;
        ALTER TABLE "Ativacao"
            ADD COLUMN IF NOT EXISTS "temperatura_id" INTEGER,
            ADD COLUMN IF NOT EXISTS "tempo_uso_id" INTEGER,
            ADD COLUMN IF NOT EXISTS "status_lampada" BOOLEAN,
            ADD COLUMN IF NOT EXISTS "data_hora" TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
        """
    )

    cursor.execute(
        """
        SELECT conname, conrelid::regclass::text
        FROM pg_constraint
        WHERE contype = 'f'
          AND conrelid::regclass::text IN ('Temperatura', 'Tempo de uso')
        """
    )
    for constraint in cursor.fetchall():
        constraint_name = constraint["conname"]
        table_name = constraint["conrelid"]
        cursor.execute(
            f'ALTER TABLE "{table_name}" DROP CONSTRAINT IF EXISTS "{constraint_name}"'
        )

    cursor.execute(
        """
        SELECT data_type
        FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = 'Tempo de uso'
          AND column_name = 'TempoLigado(minutos)'
        """
    )
    for table_name, column_name in (
        ("Tempo de uso", "TempoLigado(minutos)"),
        ("Ativacao", "TempoLigado"),
    ):
        cursor.execute(
            """
            SELECT data_type
            FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = %s
              AND column_name = %s
            """,
            (table_name, column_name),
        )
        column = cursor.fetchone()
        if column and column["data_type"] in ("timestamp without time zone", "timestamp with time zone"):
            cursor.execute(
                f'ALTER TABLE "{table_name}" ALTER COLUMN "{column_name}" '
                'TYPE DECIMAL USING NULL'
            )


def _insert(cursor, sql, values):
    if SQLITE_DATABASE:
        cursor.execute(sql, values)
        return cursor.lastrowid

    cursor.execute(sql + " RETURNING id", values)
    return cursor.fetchone()["id"]


def _parse_datetime(value):
    if isinstance(value, datetime):
        return value.replace(tzinfo=timezone.utc) if value.tzinfo is None else value
    return datetime.fromisoformat(str(value).replace("Z", "+00:00")).replace(tzinfo=timezone.utc)


def record_state_change(temperatura, lampada):
    """Registra somente uma transição e retorna (mudou, minutos_ligada)."""
    temperatura = float(temperatura)
    lampada = bool(lampada)
    agora = datetime.now(timezone.utc)
    connection = get_db_connection()
    cursor = connection.cursor()

    try:
        cursor.execute(
            'SELECT "status_lampada", "data_hora" FROM "Ativacao" ORDER BY "id" DESC LIMIT 1'
        )
        anterior = cursor.fetchone()
        estado_anterior = None if anterior is None else bool(anterior[0] if SQLITE_DATABASE else anterior["status_lampada"])

        if estado_anterior is not None and estado_anterior == lampada:
            return False, 0.0

        agora_texto = agora.isoformat() if SQLITE_DATABASE else agora
        temperatura_id = _insert(
            cursor,
            'INSERT INTO "Temperatura" ("temp", "data_hora") VALUES (%s, %s)' if not SQLITE_DATABASE else 'INSERT INTO "Temperatura" ("temp", "data_hora") VALUES (?, ?)',
            (temperatura, agora_texto),
        )

        minutos_ligada = None
        tempo_uso_id = None
        if not lampada and anterior is not None:
            data_inicio = anterior[1] if SQLITE_DATABASE else anterior["data_hora"]
            minutos_ligada = max(0.0, (agora - _parse_datetime(data_inicio)).total_seconds() / 60)
            tempo_uso_id = _insert(
                cursor,
                'INSERT INTO "Tempo de uso" ("TempoLigado(minutos)", "inicio", "fim") VALUES (%s, %s, %s)' if not SQLITE_DATABASE else 'INSERT INTO "Tempo de uso" ("TempoLigado(minutos)", "inicio", "fim") VALUES (?, ?, ?)',
                (minutos_ligada, data_inicio, agora_texto),
            )

        _insert(
            cursor,
            'INSERT INTO "Ativacao" ("temperatura_id", "tempo_uso_id", "temperatura", "TempoLigado", "status_lampada", "data_hora") VALUES (%s, %s, %s, %s, %s, %s)' if not SQLITE_DATABASE else 'INSERT INTO "Ativacao" ("temperatura_id", "tempo_uso_id", "temperatura", "TempoLigado", "status_lampada", "data_hora") VALUES (?, ?, ?, ?, ?, ?)',
            (temperatura_id, tempo_uso_id, temperatura, minutos_ligada, lampada, agora_texto),
        )
        connection.commit()
        return True, minutos_ligada or 0.0
    except Exception:
        connection.rollback()
        raise
    finally:
        cursor.close()
        connection.close()


def fetch_history(limit=50):
    connection = get_db_connection()
    cursor = connection.cursor()
    cursor.execute(
        'SELECT a."id", a."temperatura", a."status_lampada", a."data_hora", a."TempoLigado" AS "tempo_ligado_minutos" '
        'FROM "Ativacao" a ORDER BY a."id" DESC LIMIT %s' if not SQLITE_DATABASE else
        'SELECT a."id", a."temperatura", a."status_lampada", a."data_hora", a."TempoLigado" AS "tempo_ligado_minutos" '
        'FROM "Ativacao" a ORDER BY a."id" DESC LIMIT ?',
        (limit,),
    )
    rows = cursor.fetchall()
    result = []
    for row in rows:
        normalized = {}
        for key, value in dict(row).items():
            if isinstance(value, Decimal):
                normalized[key] = float(value)
            elif isinstance(value, datetime):
                normalized[key] = value.isoformat()
            else:
                normalized[key] = value
        result.append(normalized)
    cursor.close()
    connection.close()
    return result


init_db()
